const data = [
    { name: 'Jashandeep singh', email: 'jashanpreet0479@gmail.com', pending: 25 },
    { name: 'Akshay Sharma', email: 'jerryvibes.444@gmail.com', pending: 0 },
    { name: 'Ravenjeet Kaur', email: 'ravenjeetkaur@gmail.com', pending: 44 },
    { name: 'Rajni', email: 'vansh.rajni.96@gmail.com', pending: 0 },
    { name: 'Mandeep kaur', email: 'mandeep.k21@icloud.com', pending: 82 },
    { name: 'Sakshi', email: 'sakshidigra24@gmail.com', pending: 17 },
    { name: 'Husanpreet kaur', email: 'husanpreetkaur9899@gmail.com', pending: 42 },
    { name: 'Sonia Chauhan', email: 's73481109@gmail.com', pending: 13 },
    { name: 'Baljinder kaur', email: 'nikkibaljinderkaur@gmail.com', pending: 0 },
    { name: 'Jashandeep singh', email: 'jass006623@gmail.com', pending: 0 },
    { name: 'Mandeep kaur', email: 'gurnoor1311singh@gmail.com', pending: 49 },
    { name: 'Yash yadav', email: 'yy861880@gmail.com', pending: 14 },
    { name: 'Princy', email: 'princyrani303@gmail.com', pending: 28 },
    { name: 'Sejal', email: 'sejalrani72@gmail.com', pending: 0 },
    { name: 'Kiran Brar', email: 'brark5763@gmail.com', pending: 12 },
    { name: 'Payal', email: 'payalpuri3299@gmail.com', pending: 44 },
    { name: 'Joyti kaur', email: 'nasib03062003@gmail.com', pending: 0 },
    { name: 'Davinderpal kaur', email: 'hansmanraj88@gmail.com', pending: 34 },
    { name: 'Nitinluthra', email: 'nitinanku628@gmail.com', pending: 55 },
    { name: 'SEEMA RANI', email: 'ssatnam41912@gmail.com', pending: 45 },
    { name: 'Ansh', email: 'aansh8588@gmail.com', pending: 79 },
    { name: 'Manish', email: 'my440243@gmail.com', pending: 38 },
    { name: 'Preeti', email: 'preetibrarbrar7@gmail.com', pending: 13 },
    { name: 'Saloni', email: 'ananyakakkar53b@gmail.com', pending: 44 },
    { name: 'Paramjeet kaur', email: 'vilasraparam@gmail.com', pending: 0 },
    { name: 'Saijel Goel', email: 'saijelgoel4@gmail.com', pending: 35 },
    { name: 'Navpreet kaur', email: 'navpreetkaur95271@gmail.com', pending: 38 },
    { name: 'Raveena', email: 'khanrehamdin366@gmail.com', pending: 0 },
    { name: 'Kulwant Singh', email: 'kulwantsinghdhaliwalsaab668@gmail.com', pending: 135 },
    { name: 'Shivani', email: 'shivanilead2026@gmail.com', pending: 0 },
    { name: 'Priyanka', email: 'harjinderkumarkumar56@gmail.com', pending: 36 },
    { name: 'Rahul', email: 'ms0286777@gmail.com', pending: 0 },
    { name: 'Rimpy Singh', email: 'chouhansab64@gmail.com', pending: 0 },
    { name: 'Gurdeep Singh', email: 'gurdeepgill613@gmail.com', pending: 41 },
    { name: 'Resham kaur', email: 'reshamkaur6@gmail.com', pending: 24 },
    { name: 'Arshdeep singh', email: 'arshdeepjnvkauni1606@gmail.com', pending: 24 },
    { name: 'Rajinder', email: 'officialrajinderdhillon@gmail.com', pending: 37 },
    { name: 'Jasmeen singh', email: 'jasmeensingh188@gmail.com', pending: 18 },
    { name: 'Mandeep kaur', email: 'arshrandawa29@gmil.com', pending: 0 },
    { name: 'Sujal Sankhla', email: 'sujalsankhla11@gmail.com', pending: 80 },
    { name: 'Prince', email: 'prince@gmail.com', pending: 79 },
    { name: 'Mani kaur', email: 'ranimani073@gmail.com', pending: 0 },
    { name: 'Sonali', email: 'chaurasiyasonali56@gmail.com', pending: 17 },
    { name: 'Priya Arora', email: 'priyaarora50505@gmail.com', pending: 32 },
    { name: 'Jyoti', email: 'rimpy7978@gmail.com', pending: 31 },
    { name: 'Babita', email: 'babitanahar5@gmail.com', pending: 0 },
    { name: 'Simran', email: 'simrankaurdee9@gmail.com', pending: 0 },
    { name: 'Sameer', email: 'rupanasameer551@gmail.com', pending: 59 },
    { name: 'Pooja jolly', email: 'jollypooja5@gmail.com', pending: 24 },
    { name: 'Jaspreet Kaur', email: 'jaspreetkaursarao45@gmail.com', pending: 39 },
    { name: 'Rohit Kumar', email: 'rohitchandolia1243@gmail.com', pending: 0 },
    { name: 'Manjinder', email: 'rajveerbrarbrar637@gmail.com', pending: 7 },
    { name: 'Tushte', email: 'tushte756@gmail.com', pending: 0 },
    { name: 'HARDEEP KAUR', email: 'preetman00001@gmail.com', pending: 0 },
    { name: 'Komal', email: 'goldymahi27@gmail.com', pending: 61 },
    { name: 'Swati', email: 'sainsachin737@gmail.com', pending: 91 },
    { name: 'ranjodh singh', email: 'ranjodhmomi@gmail.com', pending: 66 },
    { name: 'Rahul Rai', email: 'rrai26597@gmail.com', pending: 0 },
    { name: 'Rahul kumar', email: 'rahulkumarrk1111@gmail.com', pending: 0 },
    { name: 'Loveleen', email: 'loveleensharma530@gmail.com', pending: 8 },
    { name: 'MOHIT LUDHRANI', email: 'ludhranimohit91@gmail.com', pending: 34 },
    { name: 'Harpreet kaur', email: 'harpreetk61988@gmail.com', pending: 78 },
    { name: 'Gurteshwar Singh', email: 'gurteshwargill098@gmail.com', pending: 80 },
    { name: 'Prabhjot kaur', email: 'pjot10096@gmail.com', pending: 0 },
    { name: 'PARAMJIT KAUR', email: 'paramjitkaur20890@gmail.com', pending: 16 },
    { name: 'Tanu Dhawan', email: 'dhawantanu536@gmail.com', pending: 116 },
    { name: 'Gurpreet kaur', email: 'gjama1979@gmail.com', pending: 17 },
    { name: 'Dinesh Monga', email: 'dineshmonga22@gmail.com', pending: 0 },
    { name: 'Amritpal Kaur', email: 'amritpalkaursohi358@gmail.com', pending: 39 },
    { name: 'Arshdeep kaur', email: 'arshkaur6395@gmail.com', pending: 81 },
    { name: 'Rajbinder', email: 'rajbinderkamboj123@gmail.com', pending: 0 },
    { name: 'Lalit kumar', email: 'rasganiya98775@gmail.com', pending: 0 },
    { name: 'Gurvinder Matharu', email: 'gurvindermatharu061@gmail.com', pending: 0 },
    { name: 'Seerat', email: 'bamniyareeta57@gmail.om', pending: 0 },
    { name: 'Navjot Kaur', email: 'knavjotkaur113@gmail.com', pending: 32 },
    { name: 'Sandeep Rehaan', email: 'sipreet73@gmail.com', pending: 22 },
    { name: 'Sonia', email: 'bangersonia474@gmail.com', pending: 0 },
    { name: 'Bhawna', email: 'bhawna1330@gmail.com', pending: 0 },
    { name: 'Balraj singh', email: 'bs0525765349@gmail.com', pending: 0 },
    { name: 'Mandeep kaur', email: 'mandeepkau340@gmail.com', pending: 127 },
    { name: 'VEERPAL KAUR', email: 'surjitsingh1067@gmail.com', pending: 40 },
    { name: 'Mandeep kaur', email: 'mandeepbrar1325@gmail.com', pending: 68 },
    { name: 'MUSKAN', email: 'muskanchopra376@gmail.com', pending: 32 },
    { name: 'Naina Nawani', email: 'navaninaina@gmail.com', pending: 0 },
    { name: 'Shivani', email: 'sandhu16shivani@gmail.com', pending: 0 },
    { name: 'Jashandeep kaur', email: 'jk419473@gmail.com', pending: 26 },
    { name: 'Yuail arian', email: 'aryansandhu652@gmail.com', pending: 41 },
    { name: 'Kanchan sharma', email: 'sharmaanjali93962@gmail.com', pending: 20 },
    { name: 'Test', email: 'test@gmail.com', pending: 0 },
    { name: 'Navjot kaur', email: 'rajbirsingh97843@gmail.com', pending: 0 },
    { name: 'Lakhveer kaur', email: 'lakhveerkaur219@gmail.com', pending: 0 },
    { name: 'Kirandeep kaur', email: 'kirandeepkaur7744@gmail.com', pending: 0 },
    { name: 'Lovepreet singh', email: 'lovepreetsinghvicky05@gmail.com', pending: 0 },
    { name: 'Tanisha', email: 'tanishakaur4095@gmail.com', pending: 0 },
    { name: 'Mandeep kaur', email: 'arshrandhawaarshrandhawa29@gmail.com', pending: 0 },
    { name: 'Vinita punjabi', email: 'punjabivinita@gmail.com', pending: 46 },
    { name: 'Sunita jhatta', email: 'jhattasunita@gmail.com', pending: 0 },
    { name: 'Simranpreet kaur', email: 'simransidhu792005@gmail.com', pending: 0 },
    { name: 'Kiran', email: 'kiran@gmail.com', pending: 0 },
    { name: 'Ajay kumar', email: 'ajayk783382@gmail.com', pending: 28 },
    { name: 'Akash', email: 'dbrar8826@gmail.com', pending: 14 },
    { name: 'Palak', email: 'palakgharu2025@gmail.com', pending: 0 },
    { name: 'Krishn kumari', email: 'kumarikrishna4962@gmail.com', pending: 0 },
    { name: 'Neha', email: 'neharajoria1543@gmail.com', pending: 39 },
    { name: 'JASPREET', email: 'jaspreet@gmail.com', pending: 0 },
    { name: 'Lovepreet singh', email: 'lovepreetsinghvicky05@gamil.com', pending: 0 },
    { name: 'Swinky', email: 'swinkychiku@gmail.com', pending: 0 },
    { name: 'Anita', email: 'neetteji@gmail.com', pending: 0 },
    { name: 'Suman', email: 'sumansumankaur09@gmail.com', pending: 48 },
    { name: 'SAMAN', email: 'samandeepkaur1216@gmail.com', pending: 29 },
    { name: 'Akshmala', email: 'akshmala8550@gmail.com', pending: 0 },
    { name: 'Kamal kaur', email: 'ks6485422@gmail.com', pending: 0 },
    { name: 'Rohit Kumar', email: 'rohitgagneja69@gmail.com', pending: 34 },
    { name: 'Punam', email: 'kalyanj739@gmail.com', pending: 0 },
    { name: 'Shivani Gupta', email: 'shivanigupta0276@gmail.com', pending: 0 },
    { name: 'Sohan singh', email: 'singhsohan58857@gmail.com', pending: 0 },
    { name: 'Sunaina Rani', email: 'sunainakambojk@gmail.com', pending: 0 },
    { name: 'Harmandeep kaur', email: 'harmandeepkaurmanes790@gmail.com', pending: 101 },
    { name: 'Harwinder kaur', email: 'manatsingh5600@gmail.com', pending: 0 },
    { name: 'Simran', email: 'ashok376652@gmail.com', pending: 66 },
    { name: 'Prabhjeet kaur', email: 'kaurdeep06164@gmail.com', pending: 68 },
    { name: 'Jasnoor Kaur', email: 'sranjasnoor11@gmail.com', pending: 49 },
    { name: 'Baljeet kaur', email: 'diljots027@gmail.com', pending: 0 },
    { name: 'Nazia Begam', email: 'ziana4383@gmail.com', pending: 32 },
    { name: 'Rajveer kaur', email: 'rajveerkhattra9999@gmail.com', pending: 13 },
    { name: 'Ramandeep Kaur', email: 'ramansransran6@gmail.com', pending: 0 },
    { name: 'Jashandeep Kaur', email: 'jashandeepkaur6444@gmail.com', pending: 13 },
    { name: 'Harpreet Kaur', email: 'sarojbhatti066@gmail.com', pending: 0 },
    { name: 'Jasdeep Kaur', email: 'jasdeepsra68@gmail.com', pending: 12 },
    { name: 'Himanshu Sharma', email: 'sharmahimanshu9797@gmail.com', pending: 0 },
    { name: 'Mandeep kaur', email: 'brarmandeepkaur7@gmail.com', pending: 0 },
    { name: 'Loveleen kaur', email: 'loveleenkaur8285@gmail.com', pending: 76 },
    { name: 'Shivani', email: 'sparklingsoulshivani@icloud.com', pending: 0 },
    { name: 'Manbir Singh', email: 'singhmanbir938@gmail.com', pending: 84 }

];

const totalPending = data.reduce((sum, item) => sum + item.pending, 0);
const usersWithPending = data.filter(item => item.pending > 0).length;

console.log('Total Pending Leads (Feb Only):', totalPending);
console.log('Total Users with Pending Leads (>0):', usersWithPending);
console.log('Total Users in List:', data.length);
