import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * 🎯 SEND-CRM-CONVERSION v5 — CRM outcome → Meta CAPI custom event
 *    MULTI-PIXEL FAN-OUT + ORIGIN-BASED PIXEL MATCHING
 * ═══════════════════════════════════════════════════════════════════════════
 * v5 changes (admin decision 2026-08-08) — ORIGIN-BASED PIXEL MATCHING for
 * Google-Sheet leads. Scoped so that NOTHING else changes behaviour.
 *
 *  Problem found live: this function picks the pixel from the ASSIGNED
 *  AGENT's team_code. Google-Sheet leads are generated by the sheet owner's
 *  OWN page/ads (ECO@WIN12 / "TEAM ECO SIMAR") but are mostly WORKED by
 *  TEAMFIRE agents, because ECO@WIN12 has almost no active members. Verified
 *  live on 2026-08-08: in the previous 7 days 356 of the sheet's leads were
 *  assigned to TEAMFIRE users vs only 19 to ECO@WIN12 users — so ECO@WIN12's
 *  pixel (2334725197446887) received just 2 events in 14 days and had been
 *  completely silent since 2026-08-01, while TEAMFIRE's pixel
 *  (1047115834311811) was being credited with 25 conversions belonging to
 *  ads it never ran.
 *
 *  Business impact: the ad account that actually PAID for those leads got no
 *  conversion signal, so it could not optimise delivery — directly raising
 *  its cost per lead — while the other account's signal was polluted.
 *
 *  Fix: for leads whose `source` is "GoogleSheet-<originTeam>" (that label is
 *  written at intake by sheet-lead-intake and names the team whose ads
 *  produced the lead), match the pixel by that ORIGIN team only — never by
 *  the assignee's team. Every other lead keeps the exact v4 matching
 *  (page_name match OR assignee team_code match), untouched.
 *
 *  Note: if an origin team has no active pixel_config row, the event is
 *  logged as 'skipped_no_pixel' rather than falling back to the worker's
 *  pixel — sending a conversion to the wrong ad account is worse than
 *  sending none, and the skip stays visible in capi_event_log.
 *
 * v4 changes (backend-only):
 *  - Added 'FollowUp' event (status='Follow-up').
 *  - Now invoked server-side by a DB trigger (trg_send_crm_conversion) on
 *    leads status change, instead of relying solely on a fire-and-forget
 *    call from the frontend (which could silently never fire).
 *
 * v3 changes (backend-only, no app/webhook changes):
 *  - action_source: 'system_generated'  (Meta's required value for CRM events;
 *    the old 'crm' is NOT a valid action_source enum → events mis-registered)
 *  - Better matching keys: first name (fn) + last name (ln) split correctly,
 *    state (st), and a hashed external_id. Higher EMQ = better attribution.
 *  - event_time stays fresh (now) so events are always inside Meta's 7-day window.
 *
 * Safety:
 * - Only 3 allowed event names (DB CHECK constraint + app-level validation)
 * - Idempotent PER PIXEL: capi_event_log UNIQUE(lead_id, event_name, pixel_id)
 * - Fire-and-forget: always returns 200, never throws back to the caller
 * ═══════════════════════════════════════════════════════════════════════════
 */

const ALLOWED_EVENTS = ['QualifiedLead', 'ClosedDeal', 'FollowUp'];

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

async function hashValue(val: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode((val || '').toLowerCase().trim());
  const hash = await crypto.subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, '0')).join('');
}

function formatPhone(p: string): string {
  const digits = (p || '').replace(/\D/g, '');
  if (digits.startsWith('91') && digits.length === 12) return digits;
  if (digits.length === 10) return '91' + digits;
  return digits;
}

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  );

  try {
    const { lead_id, event_name } = await req.json();

    if (!lead_id || !ALLOWED_EVENTS.includes(event_name)) {
      return new Response(JSON.stringify({ error: 'Invalid input' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // ── Fetch lead (now also state + lead_details, for better matching) ──
    const { data: lead } = await supabase
      .from('leads')
      .select('id, name, phone, city, state, source, assigned_to, lead_details')
      .eq('id', lead_id)
      .single();

    if (!lead) {
      return new Response(JSON.stringify({ error: 'Lead not found' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const pageName = (lead.source || '').replace(/^Meta - /, '');

    // Fallback match key: assigned user's team_code
    let teamCode: string | null = null;
    if (lead.assigned_to) {
      const { data: u } = await supabase.from('users').select('team_code').eq('id', lead.assigned_to).maybeSingle();
      teamCode = u?.team_code || null;
    }

    // ── v5: origin team for Google-Sheet leads (see header note) ──
    // "GoogleSheet-ECO@WIN12" -> ['ECO@WIN12']. When this is set it REPLACES
    // the assignee-based matching entirely for this lead.
    const sheetOrigin = (lead.source || '').match(/^GoogleSheet-(.+)$/i);
    const originTeams = sheetOrigin
      ? sheetOrigin[1].split(',').map((t) => t.trim()).filter(Boolean)
      : null;

    // ── Match ALL active pixel_config rows, dedupe by pixel_id ──
    const { data: pixelConfigs } = await supabase
      .from('pixel_config')
      .select('pixel_id, capi_access_token, page_name, team_code')
      .eq('is_active', true);

    const matchedPixels = new Map<string, any>(); // pixel_id -> config

    if (pixelConfigs && pixelConfigs.length > 0) {
      const sourcePage = pageName.toLowerCase();
      const teamCodesOfLead = (teamCode || '').split(',').map((t) => t.trim()).filter(Boolean);

      for (const config of pixelConfigs) {
        if (config.capi_access_token === 'PENDING_TOKEN') continue;

        const configTeams = (config.team_code || '').split(',').map((t: string) => t.trim()).filter(Boolean);

        let isMatch: boolean;

        if (originTeams) {
          // Sheet lead → ONLY the originating team's pixel (the ad account
          // that paid for this lead), never the working agent's pixel.
          isMatch = originTeams.some((t) => configTeams.includes(t));
        } else {
          // Unchanged v4 behaviour for every other lead.
          const configPage = (config.page_name || '').toLowerCase().substring(0, 25);
          const pageMatch = sourcePage && (sourcePage.includes(configPage) || configPage.includes(sourcePage.substring(0, 25)));
          const teamMatch = teamCodesOfLead.some((t) => configTeams.includes(t));
          isMatch = !!(pageMatch || teamMatch);
        }

        if (isMatch && !matchedPixels.has(config.pixel_id)) {
          matchedPixels.set(config.pixel_id, config);
        }
      }
    }

    if (matchedPixels.size === 0) {
      const { data: existingSkip } = await supabase
        .from('capi_event_log')
        .select('id')
        .eq('lead_id', lead_id)
        .eq('event_name', event_name)
        .is('pixel_id', null)
        .maybeSingle();

      if (!existingSkip) {
        await supabase.from('capi_event_log').insert({
          lead_id, event_name, pixel_id: null, result: 'skipped_no_pixel'
        });
      }
      return new Response(JSON.stringify({ status: 'skipped_no_pixel' }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // ── Hash once, reuse for every pixel ──
    // Split full name into first + last for correct Meta matching (fn/ln).
    const nameParts = (lead.name || '').trim().split(/\s+/).filter(Boolean);
    const firstName = nameParts[0] || '';
    const lastName = nameParts.length > 1 ? nameParts.slice(1).join(' ') : '';

    const hashedPhone = await hashValue(formatPhone(lead.phone));
    const hashedFirst = firstName ? await hashValue(firstName) : '';
    const hashedLast = lastName ? await hashValue(lastName) : '';
    const hashedCity = lead.city && lead.city.toLowerCase() !== 'unknown' ? await hashValue(lead.city) : '';
    const hashedState = lead.state ? await hashValue(lead.state) : '';
    const hashedCountry = await hashValue('in');
    const hashedExternalId = await hashValue(String(lead.id));
    // Email match-key (2026-08-14) — read from lead_details.Email (populated
    // by sheet-lead-intake for sheet-sourced leads). These status-change
    // events (QualifiedLead/ClosedDeal/FollowUp) are the ones ad optimization
    // actually relies on, so this matters more than the initial Lead event.
    const rawEmail = (lead.lead_details?.Email || '').toString().trim().toLowerCase();
    const hashedEmail = rawEmail && isValidEmail(rawEmail) ? await hashValue(rawEmail) : '';

    // Build user_data with only the keys we actually have (Meta ignores empties,
    // but omitting them keeps the payload clean and match quality accurate).
    const userData: Record<string, any> = {
      ph: [hashedPhone],
      country: [hashedCountry],
      external_id: [hashedExternalId],
    };
    if (hashedFirst) userData.fn = [hashedFirst];
    if (hashedLast) userData.ln = [hashedLast];
    if (hashedCity) userData.ct = [hashedCity];
    if (hashedState) userData.st = [hashedState];
    if (hashedEmail) userData.em = [hashedEmail];

    const results: any[] = [];

    for (const [pixelId, config] of matchedPixels) {
      const { data: existing } = await supabase
        .from('capi_event_log')
        .select('id, result')
        .eq('lead_id', lead_id)
        .eq('event_name', event_name)
        .eq('pixel_id', pixelId)
        .maybeSingle();

      if (existing && existing.result === 'sent') {
        results.push({ pixel_id: pixelId, status: 'already_sent' });
        continue;
      }

      const capiPayload = {
        data: [{
          event_name,
          event_id: `${event_name}_${lead_id}_${pixelId}`,
          event_time: Math.floor(Date.now() / 1000),
          action_source: 'system_generated',
          user_data: userData,
          custom_data: {
            event_source: 'crm',
            lead_event_source: 'LeadFlow CRM',
          },
        }],
      };

      try {
        const capiResp = await fetch(
          `https://graph.facebook.com/v18.0/${pixelId}/events?access_token=${config.capi_access_token}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(capiPayload),
          }
        );

        const capiResult = await capiResp.json();
        const ok = capiResp.ok && !capiResult.error;

        await supabase.from('capi_event_log').upsert({
          lead_id, event_name, pixel_id: pixelId,
          result: ok ? 'sent' : 'failed',
          response: capiResult
        }, { onConflict: 'lead_id,event_name,pixel_id' });

        results.push({ pixel_id: pixelId, status: ok ? 'sent' : 'failed', detail: capiResult });
      } catch (pixelErr: any) {
        await supabase.from('capi_event_log').upsert({
          lead_id, event_name, pixel_id: pixelId,
          result: 'failed',
          response: { error: pixelErr.message }
        }, { onConflict: 'lead_id,event_name,pixel_id' });
        results.push({ pixel_id: pixelId, status: 'failed', error: pixelErr.message });
      }
    }

    return new Response(JSON.stringify({ status: 'done', pixels: results }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (e: any) {
    console.error('send-crm-conversion error:', e.message);
    return new Response(JSON.stringify({ error: e.message }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
